FIX: Plugin crashes if `fixed` is set to true and `style` is set to undefined
TaylorBriggs/react-native-typewriter pull request #10
Opened 2017-06-08 14:47 UTC by nabilfreeman

2017-06-08 14:48 UTC, nabilfreeman commented
cc @TaylorBriggs - can you review this pull request?

2017-06-09 22:50 UTC, TaylorBriggs requested changes
I think the one change to use `defaultProps` makes sense since that's already in place.

2017-06-09 22:50 UTC, TaylorBriggs commented on index.js
> +          style={[...(props.style || {}), invisibleStyle]}
It would be more idiomatic to add this to `defaultProps` above.

2017-08-25 21:11 UTC, TaylorBriggs commented
Closed by https://github.com/TaylorBriggs/react-native-typewriter/commit/5f03a4acc6c19dce9964c990011b5712ba959b25

2017-08-25 21:11 UTC, closed without merging